kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31000
    hostPort: 443
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32000
    hostPort: 15021
    listenAddress: "127.0.0.1"
    protocol: TCP
