
apiVersion: v1
kind: Service
metadata:
  name: giggle-box
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: giggle-box
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: giggle-box-v1
  labels:
    app: giggle-box
    version: v1
spec:
  selector:
    matchLabels:
      app: giggle-box
  template:
    metadata:
      labels:
        app: giggle-box
        version: v1
    spec:
      containers:
      - image: kishanb/slow-http:1.0.1
        name: giggle-box
        env:
          - name: DELAY_RESPONSE
            value: 0.1s
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 200M
          requests:
            cpu: 10m
            memory: 50M
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - name: 'giggle-box'
    match:
    - uri:
        prefix: /giggle-box
    rewrite:
      uri: "/"
    route:
    - destination:
        host: giggle-box
        port:
          number: 8080
    timeout: 0.5s
