apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
  - name: simple-app
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "Incoming Traffic! $i"; i=$((i+1)); sleep 1; done']
